development:
  adapter: mysql2
  encoding: utf8
  database: guitardb_development
  pool: 5
  username: hoyamada
  password: orih6254
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: guitardb
  pool: 5
  username: hoyamada
  password: orih6254
  host: localhost
